London Class 8 - Davood Khoshnood - JavaScript - Core 1 - Week 1
CodeYourFuture/JavaScript-Core-1-Coursework-Week1 pull request #237
Opened 2021-12-14 19:24 UTC by DavoodKhoshnood

**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

# Notes

- What did you find easy?

- What did you find hard?

- What do you still not understand?

- Any other notes?

2021-12-17 15:23 UTC, teniolao requested changes

2021-12-18 18:38 UTC, DavoodKhoshnood commented on exercises/L-functions-nested/exercise.js
>  var mentor1 = "Daniel";
Hi Teniolao, I've changed and committed it again. thanks.

2022-01-02 15:52 UTC, DiegoJunior0 commented on mandatory/1-syntax-errors.js
> +})
I assume you didn't mean to change all these tests, I assume from a change all? Be careful when doing this when tests are in the same file (though in the real world that wouldn't be case!)

2022-01-02 15:53 UTC, DiegoJunior0 commented
Excellent work Davood!

2022-01-05 07:20 UTC, DavoodKhoshnood commented
> Excellent work Davood!
Thanks Henry!

2023-03-04 10:44 UTC, closed without merging