ZA2-Harerimana-Dieudonne-JavaScript-Core-1-Coursework-Week1
CodeYourFuture/JavaScript-Core-1-Coursework-Week1 pull request #307
Opened 2022-07-06 21:44 UTC by diegoharera

**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

# Notes

- What did you find easy?

- What did you find hard?

- What do you still not understand?

- Any other notes?

2022-07-08 09:58 UTC, BereniceOgundele reviewed
Hi Harerimana, it looks like you put in a lot of time and effort to complete these exercises. Well done for hanging in there and completing it. All the best going forward...your code looks good.

2022-08-13 13:50 UTC, lexyking requested changes
Left few comments but overall great jobs.

2022-08-13 13:50 UTC, lexyking commented on mandatory/4-tax.js
>  /*
Great job on these functions, Can you please have a look at the other function ??

2022-08-13 13:50 UTC, lexyking commented on mandatory/3-function-output.js
>  }
Amazing.

2022-08-13 13:50 UTC, lexyking commented on mandatory/2-logic-error.js
> +  return word.length();
`length` is not called with the `()`

2022-08-13 13:50 UTC, lexyking commented on mandatory/1-syntax-errors.js
> +  return "Hello, my name is " + name + " and I am " + age + " years old";
Well done on this one, I like your attention to detail on those empty spaces.

2022-08-13 13:50 UTC, lexyking commented on exercises/L-functions-nested/exercise.js
> +console.log(greet(mentor5));
Well done

2022-08-13 13:50 UTC, lexyking commented on exercises/K-functions-parameters/exercise.js
> -
Well done.

2022-08-13 13:50 UTC, lexyking commented on exercises/K-functions-parameters/exercise2.js
> +var result = divide(1.5, 2);
Well done

2022-08-13 13:50 UTC, lexyking commented on exercises/K-functions-parameters/exercise3.js
> +var greeting = createGreeting("Diego");
Well done

2022-08-13 13:50 UTC, lexyking commented on exercises/K-functions-parameters/exercise4.js
>  console.log(sum);
Nice

2022-08-13 13:50 UTC, lexyking commented on exercises/K-functions-parameters/exercise5.js
> +const greeting = createLongGreeting("Diego", 30);
Well done

2022-08-13 13:50 UTC, lexyking commented on exercises/J-functions/exercise2.js
>  }
Nice

2022-08-13 13:50 UTC, lexyking commented on exercises/J-functions/exercise.js
Nice

2022-08-13 13:50 UTC, lexyking commented on exercises/I-floats/exercise.js
> +console.log("Percentage students:", mentorsResult + "%");
Great job!

2022-08-13 13:50 UTC, lexyking commented on exercises/G-numbers/exercise.js
> +console.log("Total number of students and mentors:", total);
Well done.

2022-08-13 13:50 UTC, lexyking commented on exercises/F-strings-methods/exercise2.js
> +const message = name.trim();
Good use of the `.trim` method but the ask was to rewrite the same message as above.

2022-08-13 13:50 UTC, lexyking commented on exercises/F-strings-methods/exercise.js
> +let message = "hello,my name is " + name + " and my name is " + amount + " characters long";
Well done.

2022-08-13 13:50 UTC, lexyking commented on exercises/E-strings-concatenation/exercise.js
> +console.log(greeting);
Great.

2022-08-13 13:50 UTC, lexyking commented on exercises/D-strings/exercise.js
> +console.log(typeof message);
Well done.

2022-08-13 13:50 UTC, lexyking commented on exercises/C-variables/exercise.js
> +console.log(greeting);
Well done.

2022-08-13 13:50 UTC, lexyking commented on exercises/B-hello-world/exercise.js
> +console.log(39);
Well done.

2023-03-04 10:32 UTC, closed without merging