Javascript core-1
CodeYourFuture/JavaScript-Core-1-Coursework-Week1 pull request #70
Opened 2021-01-22 21:44 UTC by MSUMBA-art

# Your Details

- Your Name: Alexander
- Your City: Cape Town South Africa
- Your Slack Name: Alexander Msumba

# Homework Details

- Module: JavaScript-Core-1-Week1

- Week: 1

2021-01-22 21:51 UTC, KudahShambare commented
Hello, Alexander. Your pull request title should be in the City Name Module and WEEK

2021-01-22 21:56 UTC, MSUMBA-art commented
Thanks, edited. I was rushing for time 🤣🤣🤣🤣 poor me

On Fri., 22 Jan. 2021, 23:51 KudahShambare, <notifications@github.com>
wrote:

> Hello, Alexander. Your pull request title should be in the City Name
> Module and WEEK
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/pull/70#issuecomment-765704891>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQBIJP2ALSR2DQX4RNOKW2DS3HXNVANCNFSM4WPCTJTA>
> .
>

2021-01-22 22:49 UTC, SerialCarKey requested changes
Hi Alexander, clean code on most of the Mandatory, however the syntax and logical error,js is still showing small issues.

function trimWord(word) {
  return trimWord();
}
for example .

the code needs to be reviewed, you can run to test the code & see if you passed on the terminal.

If you need any assistance, feel free to contact me anytime.

2021-01-23 05:07 UTC, MSUMBA-art commented
Thanks buddy, I will fix

On Sat., 23 Jan. 2021, 00:50 SerialCarKey, <notifications@github.com> wrote:

> *@SerialCarKey* requested changes on this pull request.
>
> Hi Alexander, clean code on most of the Mandatory, however the syntax and
> logical error,js is still showing small issues.
>
> function trimWord(word) {
> return trimWord();
> }
> for example .
>
> the code needs to be reviewed, you can run to test the code & see if you
> passed on the terminal.
>
> If you need any assistance, feel free to contact me anytime.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/pull/70#pullrequestreview-574678789>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQBIJP4GR4FWRUOL6RYOUN3S3H6KHANCNFSM4WPCTJTA>
> .
>

2021-01-27 14:00 UTC, KudahShambare commented
I have realised that your pull request is popping up a conflicting files notice. I tried to check it out but I couldn't identify the problem.

2021-01-31 15:20 UTC, theTrainMan reviewed
Looking great

2021-03-28 22:33 UTC, he-man-david commented on exercises/I-floats/exercise.js
> +let percentageStudents = Math.round((numberOfStudents / total) * 100);
great job!

2021-03-28 22:33 UTC, he-man-david commented on exercises/K-functions-parameters/exercise2.js
> +function divide() {
where are the params?

2021-03-28 22:33 UTC, he-man-david commented on exercises/K-functions-parameters/exercise3.js
> +    return "Hello my name is Daniel";
where is name param used?

2021-03-28 22:34 UTC, he-man-david commented on mandatory/1-syntax-errors.js
> +    total = a + b;
avoid declaring global variables like this https://stackoverflow.com/questions/10525582/why-are-global-variables-considered-bad-practice

2021-05-13 13:17 UTC, closed without merging